### ISSUE TITLE
eprints2rdm: rights mapping

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/caltechauthors#70]
Rights is currently missing the description field. It should be like

```
{
title: {
en: "Other"
},
description: {
en: "No commercial reproduction, distribution, display or performance rights in this work are provided"
}
}
]
```

Also, remove the mapping of the note field into rights. We already have note as a description field.

**Comment by rsdoiel** [comment]
Looking at the logic I spotted a mis map between the title and description. I am removing the Notes mapping. These changes will be in the upcoming release v0.0.47.
