### ISSUE TITLE
eprints2rdm: wrong publication date

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/caltechauthors#75]
Example 57302. It's not taking 1917-09 from the date field, but there doesn't seem to be any obvious difference from other eprints records. Result: https://authors.library.caltech.edu/records/05vkb-5ky09

**Comment by rsdoiel** [comment]
The cause is that the date_type element is an empty string (in this example). The possible values for date type are 
NULL, "", "completed", "inpress", "published", "submitted".  I think I can treat an empty string as "published" but am still analyzing the data.

**Comment by rsdoiel** [comment]
This is fixed in the upcoming v0.0.44 release of irdmtools.
